webtalk_init -webtalk_dir F:/Digital System Designing using Verilog/System-Design-Using-VerilogHDL/Gate Levl Modelling/7_1bitComparator/7_1bitComparator.sim/sim_1/behav/xsim/xsim.dir/comparator_1bit_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Aug  9 01:03:38 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d100c2a6-068a-4bd4-b3dc-eab40de70330" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "70960b5c7a7043148fc836868c3aefca" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx  " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2096 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "6.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "25 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6752_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1869829036 -regid "" -xml F:/Digital System Designing using Verilog/System-Design-Using-VerilogHDL/Gate Levl Modelling/7_1bitComparator/7_1bitComparator.sim/sim_1/behav/xsim/xsim.dir/comparator_1bit_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html F:/Digital System Designing using Verilog/System-Design-Using-VerilogHDL/Gate Levl Modelling/7_1bitComparator/7_1bitComparator.sim/sim_1/behav/xsim/xsim.dir/comparator_1bit_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm F:/Digital System Designing using Verilog/System-Design-Using-VerilogHDL/Gate Levl Modelling/7_1bitComparator/7_1bitComparator.sim/sim_1/behav/xsim/xsim.dir/comparator_1bit_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
